folderin: /home/user2/tst
folderout: /home/user2/out
folderext: /home/user2/folder1
folderext3: /home/user2/folder3
count: 5
bs: 10K
folderbad: /home/user2/folder2
type: zip
logfolder: /home/user2/log_folder
ip: 0.0.0.0
user: user2
passwd: "11"
pkgname: p7zip-full